name = "aidu-proxy"
main = "worker.js"
compatibility_date = "2024-02-03"

[vars]
# You can add non-sensitive vars here
# API_VERSION = "v1"

# Note: GEMINI_API_KEY and ZHIPU_API_KEY should be set using 
# wrangler secret put <KEY_NAME>

[[kv_namespaces]]
binding = "AIDU_LIMITS"
id = "254c24f7e26b43a9a0ca3f5464170805"
